name: Deploy To Bluehost

on:
  push:
    branches: [ "master" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Backend
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: 162.241.217.168
          user: wxqbnfmy
          key: ${{secrets.SSH_KEY}}
          first_ssh: |
            cd /home2/wxqbnfmy/forms.codepresso.net
            git reset --hard
            git switch master
            git pull origin master
            yes | composer install --optimize-autoloader --no-dev --prefer-dist
            php artisan migrate:fresh --seed --force
            php artisan optimize:clear
